name: Publish ComfyUI Scripting Tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Lint Python files
        run: |
          pip install flake8
          flake8 src --max-line-length=120
      - name: Check metadata file
        run: |
          test -f comfyui_scripting_tools.json
      - name: Show publish instructions
        run: |
          echo "To publish this package, follow the instructions at https://registry.comfy.org/docs/publish-extension/"

  publish:
    name: "📦 Publish Custom Node"
    needs: build-and-check
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish to ComfyUI Registry
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
